#!/usr/bin/env python3
"""Export a trained 16-band vowel GMM JSON as Rust const arrays."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import sys

VOWEL_LABEL_ORDER = ["A", "I", "U", "E", "O"]
BAND_FEATURE_COUNT = 16


class ExportError(ValueError):
    pass


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export train_gmm.py JSON to src/trained_band_gmm.rs.")
    parser.add_argument("--input", required=True, type=Path, help="Input JSON from scripts/train_gmm.py")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("src/trained_band_gmm.rs"),
        help="Output Rust source path",
    )
    return parser.parse_args(argv)


def require_finite_numbers(model: dict[str, object], key: str) -> list[float]:
    values = model.get(key)
    if not isinstance(values, list):
        raise ExportError(f"{key} must be a list")
    output = []
    for value in values:
        number = float(value)
        if not math.isfinite(number):
            raise ExportError(f"{key} contains a non-finite value")
        output.append(number)
    return output


def validate_model(model: dict[str, object]) -> dict[str, object]:
    labels = model.get("labels")
    if labels != VOWEL_LABEL_ORDER:
        raise ExportError(f"labels must be {VOWEL_LABEL_ORDER!r} for a band vowel GMM")

    feature_columns = model.get("feature_columns")
    if not isinstance(feature_columns, list) or len(feature_columns) != BAND_FEATURE_COUNT:
        raise ExportError("band GMM must contain exactly 16 feature columns")
    expected_columns = [f"band_{index:02d}" for index in range(BAND_FEATURE_COUNT)]
    if feature_columns != expected_columns:
        raise ExportError(f"feature columns must be {expected_columns!r}")

    if model.get("feature_prefix") != "band_":
        raise ExportError("feature_prefix must be 'band_' for src/trained_band_gmm.rs")

    num_classes = int(model.get("num_classes", 0))
    num_mixtures = int(model.get("num_mixtures", 0))
    if num_classes != len(VOWEL_LABEL_ORDER):
        raise ExportError("num_classes must be 5")
    if num_mixtures < 1:
        raise ExportError("num_mixtures must be at least 1")

    means = require_finite_numbers(model, "means")
    inv_vars = require_finite_numbers(model, "inv_vars")
    log_weights = require_finite_numbers(model, "log_weights")
    class_priors = require_finite_numbers(model, "class_priors")

    expected_params = num_classes * num_mixtures * BAND_FEATURE_COUNT
    expected_mixtures = num_classes * num_mixtures
    if len(means) != expected_params:
        raise ExportError(f"means length must be {expected_params}")
    if len(inv_vars) != expected_params:
        raise ExportError(f"inv_vars length must be {expected_params}")
    if len(log_weights) != expected_mixtures:
        raise ExportError(f"log_weights length must be {expected_mixtures}")
    if len(class_priors) != num_classes:
        raise ExportError("class_priors length must be 5")

    return {
        "labels": labels,
        "num_classes": num_classes,
        "num_mixtures": num_mixtures,
        "num_features": BAND_FEATURE_COUNT,
        "means": means,
        "inv_vars": inv_vars,
        "log_weights": log_weights,
        "class_priors": class_priors,
    }


def rust_float(value: float) -> str:
    if abs(value) < 1.0e-12:
        value = 0.0
    text = f"{value:.9g}"
    if "e" not in text and "." not in text:
        text += ".0"
    return f"{text}_f32"


def rust_float_array(name: str, values: list[float]) -> str:
    lines = [f"pub const {name}: [f32; {len(values)}] = ["]
    for offset in range(0, len(values), 8):
        chunk = values[offset : offset + 8]
        lines.append("    " + ", ".join(rust_float(value) for value in chunk) + ",")
    lines.append("];\n")
    return "\n".join(lines)


def render_rust(model: dict[str, object]) -> str:
    labels = model["labels"]
    num_classes = int(model["num_classes"])
    num_mixtures = int(model["num_mixtures"])
    num_features = int(model["num_features"])
    label_literals = ", ".join(json.dumps(label) for label in labels)
    return "".join(
        [
            "// @generated by scripts/export_gmm_rust.py\n",
            "// This is the trained 16-band vowel GMM used by LIPSYNC_FLAG_GMM.\n",
            "// If these arrays are empty, trained_band_vowel_gmm() falls back to\n",
            "// gmm::placeholder_vowel_gmm(), which is infrastructure only and not an accuracy model.\n\n",
            "use crate::gmm::{placeholder_vowel_gmm, DiagonalGmm};\n\n",
            "pub const GMM_MODEL_KIND_NOT_USED: u32 = 0;\n",
            "pub const GMM_MODEL_KIND_PLACEHOLDER: u32 = 1;\n",
            "pub const GMM_MODEL_KIND_TRAINED: u32 = 2;\n\n",
            f"pub const TRAINED_BAND_GMM_CLASSES: [&str; {num_classes}] = [{label_literals}];\n",
            f"pub const TRAINED_BAND_GMM_MIXTURES: usize = {num_mixtures};\n",
            f"pub const TRAINED_BAND_GMM_FEATURES: usize = {num_features};\n\n",
            rust_float_array("TRAINED_BAND_GMM_MEANS", model["means"]),
            rust_float_array("TRAINED_BAND_GMM_INV_VARS", model["inv_vars"]),
            rust_float_array("TRAINED_BAND_GMM_LOG_WEIGHTS", model["log_weights"]),
            rust_float_array("TRAINED_BAND_GMM_CLASS_PRIORS", model["class_priors"]),
            TRAINED_FUNCTION,
        ]
    )


TRAINED_FUNCTION = """pub fn trained_band_vowel_gmm_model_kind() -> u32 {
    model_kind_for_shape(
        TRAINED_BAND_GMM_CLASSES.len(),
        TRAINED_BAND_GMM_MIXTURES,
        TRAINED_BAND_GMM_FEATURES,
        TRAINED_BAND_GMM_MEANS.len(),
        TRAINED_BAND_GMM_INV_VARS.len(),
        TRAINED_BAND_GMM_LOG_WEIGHTS.len(),
        TRAINED_BAND_GMM_CLASS_PRIORS.len(),
    )
}

pub(crate) fn model_kind_for_shape(
    num_classes: usize,
    num_mixtures: usize,
    num_features: usize,
    means_len: usize,
    inv_vars_len: usize,
    log_weights_len: usize,
    class_priors_len: usize,
) -> u32 {
    let expected_params = num_classes * num_mixtures * num_features;
    let expected_mixtures = num_classes * num_mixtures;
    if num_classes == 0
        || num_mixtures == 0
        || num_features == 0
        || means_len != expected_params
        || inv_vars_len != expected_params
        || log_weights_len != expected_mixtures
        || class_priors_len != num_classes
    {
        GMM_MODEL_KIND_PLACEHOLDER
    } else {
        GMM_MODEL_KIND_TRAINED
    }
}

pub fn trained_band_vowel_gmm() -> DiagonalGmm {
    if trained_band_vowel_gmm_model_kind() != GMM_MODEL_KIND_TRAINED {
        return placeholder_vowel_gmm();
    }

    DiagonalGmm {
        num_classes: TRAINED_BAND_GMM_CLASSES.len(),
        num_mixtures: TRAINED_BAND_GMM_MIXTURES,
        num_features: TRAINED_BAND_GMM_FEATURES,
        means: &TRAINED_BAND_GMM_MEANS,
        inv_vars: &TRAINED_BAND_GMM_INV_VARS,
        log_weights: &TRAINED_BAND_GMM_LOG_WEIGHTS,
        class_priors: &TRAINED_BAND_GMM_CLASS_PRIORS,
    }
}
"""


def main(argv: list[str]) -> int:
    try:
        args = parse_args(argv)
        with args.input.open(encoding="utf-8") as handle:
            raw_model = json.load(handle)
        model = validate_model(raw_model)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(render_rust(model), encoding="utf-8")
        return 0
    except (OSError, ExportError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
