name: Build for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install MinGW toolchain
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Windows DLL
        uses: actions/upload-artifact@v4
        with:
          name: lip_sync-windows-x86_64
          path: target/x86_64-pc-windows-gnu/release/lip_sync.dll
